# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java: [11, 16]

    steps:
    - uses: actions/checkout@v2
    - name: Setup Java JDK
      uses: actions/setup-java@v2
      with:
        java-version: ${{ matrix.java }}
        distribution: 'adopt'
    - name: Side-load dependencies
      run: |
        git clone --depth 1 https://github.com/fastily/jwiki.git
        pushd jwiki
        ./gradlew publishToMavenLocal -x signMavenJavaPublication
        popd
    - name: Build with Gradle
      run: ./gradlew build
